apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort  #expose to outsite users
  ports:
   - name: "result-service"
     port: 8080
     targetPort: 80
     nodePort: 30081
  selector:
     app: result  

  