apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort  #expose to outsite users
  ports:
   - name: "db-service"
     port: 8080
     targetPort: 80
     nodePort: 30080
  selector:
     app: vote 

  